### ISSUE TITLE
problem with python 3.5 and connect to Tool labs

### ISSUE THREAD

**Issue by bl79** [Krinkle/pywiki-fileprotectionsync#6]
Occurs error "NotImplementedError". In db.py is string:
`    if sys.version[0] == '3':
        raise NotImplementedError`

I also want to sure it connects to a replica DB? 
Because it requires two connections: 1) host/user/password or key file for SSH-connect, 2) and host/user/password for database-connect. But in code of script I see data only for one a connection.

**Comment by Krinkle** [comment]
This project does not connect to a database in any way (there is no file named `db.py`). Maybe you accidentally created the issue in a different project?

**Comment by bl79** [comment]
You right, sorry. Delete this post please.
